HW/custom_users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.AuthLoginView.as_view(), name='login'),
    path('logout/', views.AuthLogoutView.as_view(), name='logout'),
    path('users/', views.UsersListView.as_view(), name='user_list'),
]

HW/main_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movies.urls')),
    path('', include('parser_app.urls')),
    path('', include('custom_users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

HW/movies/urls.py
from django.urls import path
from . import views


app_name = 'movies'

urlpatterns = [
    path('', views.ItemsView.as_view(), name='movies'),
    path('create_movies_item/', views.CreateView.as_view(), name='create_movies_item'),
    path('delete_movies_item/', views.DeleteView.as_view(), name='delete_movies_item'),
    path('edit_movies_item/', views.UpdateView.as_view(), name='edit_movies_item'),
    path('search/', views.SearchView.as_view(), name='search')
]

HW/parser_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('parser_cars', views.ParserFormView.as_view(), name='parser_cars'),
]

HW/custom_users/models.py
from django.db import models
from django.contrib.auth.models import User


MALE = 1
FEMALE = 2
UNDEFINED = 3

GENDER_TYPE = (
    (MALE, 'М'),
    (FEMALE, 'Ж'),
    (UNDEFINED, 'Другое')
)


class CustomUser(User):
    phone_number = models.CharField(max_length=13, default='+996', verbose_name='Укажите номер телефона')
    date_of_birth = models.DateField(verbose_name='Увкажите дату рождения')
    gender = models.CharField(max_length=10, choices=GENDER_TYPE, verbose_name='Ваш пол')

HW/movies/models.py
from django.db import models


# Create your models here.
class Item(models.Model):
    GENRE = (
        ('Драма', 'Драма'),
        ('Ужасы', 'Ужасы'),
        ('Экшен', 'Экшен'),
        ('Слэшер', 'Слэшер'),
        ('Криминал', 'Криминал'),
    )
    name = models.CharField(max_length=54)
    image = models.ImageField(upload_to='')
    duration = models.IntegerField()
    genre = models.CharField(max_length=54, choices=GENRE)
    description = models.TextField(null=True)
    trailer = models.URLField(null=True)
    watch = models.URLField(null=True)

    def __str__(self):
        return self.name

HW/parser_app/models.py
from django.db import models


class CarsModel(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    price = models.CharField(max_length=255)
    image = models.ImageField(upload_to='')

    def __str__(self):
        return self.title

HW/custom_users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from . import models

MALE = 1
FEMALE = 2
UNDEFINED = 3

GENDER_TYPE = (
    (MALE, 'М'),
    (FEMALE, 'Ж'),
    (UNDEFINED, 'Другое')
)


class CustomUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    phone_number = forms.CharField(required=True, initial='+996', label='Укажите номер телефона')
    date_of_birth = forms.DateField(required=True, widget=forms.DateInput(attrs={'type': 'date'}))
    gender = forms.ChoiceField(choices=GENDER_TYPE, required=True)

    class Meta:
        model = models.CustomUser
        fields = (
            'username',
            'email',
            'password1',
            'password2',
            'first_name',
            'last_name',
            'phone_number',
            'date_of_birth',
            'gender',
        )

    def save(self, commit=True):
        user = super(CustomUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['firstname']
        user.last_name = self.cleaned_data['lastname']

        if commit:
            user.save()
        return user

HW/movies/forms.py
from django import forms
from . import models


class MovieForm(forms.ModelForm):
    class Meta:
        model = models.Item
        fields = '__all__'

HW/parser_app/forms.py
from django import forms
from . import models, parser


class ParserForm(forms.Form):
    MEDIA_CHOICES = ('cars.kg', 'cars.kg')
    media_type = forms.ChoiceField(choices=MEDIA_CHOICES)

    class Meta:
        fields = ['media_type']

    def parser_data(self):
        if self.data['media_type'] == 'cars.kg':
            cars_parser = parser.parser_cars()
            for i in cars_parser:
                models.CarsModel.objects.create(**i)

HW/custom_users/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse
from django.views.generic import CreateView, ListView
from django.urls import reverse_lazy
from . import forms


class RegisterView(CreateView):
    # form_class = UserCreationForm
    form_class = forms.CustomUserForm
    template_name = 'users/register.html'
    success_url = '/login/'


class AuthLoginView(LoginView):
    form_class = AuthenticationForm
    template_name = 'users/login.html'

    def get_success_url(self):
        return reverse('users:user_list')


class AuthLogoutView(LoginView):
    next_page = reverse('users:login')


class UsersListView(ListView):
    model = User
    template_name = 'users/list.html'

    def get_queryset(self):
        return self.model.objects.all()

HW/movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from . import models, forms
from django.urls import reverse
from django.views import generic


# READ
class ItemsView(generic.ListView):
    template_name = 'movies/movies.html'
    model = models.Item

    def get_queryset(self):
        return self.model.objects.all()


# CREATE
class CreateView(generic.CreateView):
    template_name = 'crud/create_movies_item.html'
    model = models.Item
    form_class = forms.MovieForm

    success_url = '/'

    def form_valid(self, form):
        print(form.cleaned_data)
        return super(CreateView, self).form_valid(form=form)


# DELETE
class DeleteView(generic.DeleteViewView):
    template_name = 'crud/delete/delete_movies_item.html'
    model = models.Item
    success_url = 'delete_movies_item'

    def get_object(self, **kwargs):
        movie_id = self.kwargs.get('id')
        return get_object_or_404(models.Item, id=movie_id)


# UPDATE
class UpdateView(generic.UpdateView):
    template_name = 'crud/update/update_movies_item.html'
    model = models.Item
    success_url = 'edit_movies_item'

    def get_object(self, **kwargs):
        movie_id = self.kwargs.get('id')
        return get_object_or_404(models.Item, id=movie_id)

    def form_valid(self, form):
        print(form.cleaned_data)
        return super(UpdateView, self).form_valid(form=form)


class SearchView(generic.ListView):
    template_name = 'movies/movies.html'
    paginate_by = 10

    def get_queryset(self):
        return models.Movie.objects.filter(name__icontains=self.request.GET.get('q'))

    def get_context_data(self, **kwargs):
        context = super(SearchView, self).get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q')
        return context

HW/parser_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import FormView, ListView
from . import models, forms, parser


class ParserFormView(FormView):
    template_name = 'parser.html'
    form_class = forms.ParserForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.parser_data()
            return HttpResponse('Данные извлечены')
        else:
            return super(ParserFormView).post(request, *args, **kwargs)

HW/templates/crud/create_movies_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movies Item creating</title>
</head>
<body>

<h1>Добавить фильм</h1>
<form action="/create_movie_item/" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Добавить</button>
</form>

</body>
</html>

HW/templates/crud/delete/delete_movies_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    st
</head>
<body>

<h1>Выберите объект для удаления</h1>
<ul>
    {% for i in delete_movies_item %}
    <li>
        <h2>{{i.name}}</h2>
        <button>
            <a href="/movies_item_drop/{{i.id}}/delete/">Удалить</a>
        </button>
    </li>
    {% endfor %}
</ul>
</body>
</html>

HW/templates/crud/update/edit_movies_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Выберите объект для редактирования</h1>
    <ul>
        {% for i in edit_movies_item %}
        <li>
            <h2>{{i.name}}</h2>
            <button>
                <a href="#">Редактировать</a>
            </button>
        </li>
        {% endfor %}
    </ul>
</body>
</html>

HW/templates/crud/update/movies_item_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>Выберите объект для редактирования</h1>
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
    <button type="submit"><a href="/edit_movies_item/{{i.idj}}/update/">Редактировать</a></button>
</form>

</body>
</html>

HW/templates/movies/movies.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: sans-serif;
            color: #333;
        }

        .container {
            padding: 0 100px;
            background-color: firebrick;
            height: 100%;
        }

        .box {
            padding: 20px 50px;
            background-color: #fffaf7;
            height: 100%;
        }

        .title {
            font-size: 54px;
            border-bottom: 4px solid #333333;
            padding: 0 0 30px 0;
        }

        .movies_item {
            list-style: none;
            margin: 100px 0 0 0;
        }

        .info {
            display: flex;
            justify-content: space-around;
            align-items: center;
            margin: 40px 0 20px 0;
        }

        .info > div > img {
            width: 340px;
            margin: 28px 0 0 0;
        }

        .info > div:last-child {
            width: 55%;
        }

        .genre {
            margin: 28px 0;
        }

        .genre > span:first-child {
            color: #555;
        }

        .genre > span:last-child {
            font-size: 26px;
            font-weight: 700;
            margin: 28px 0;
        }

        .description {
            line-height: 140%;
        }

        .duration {
            color: grey;
            margin: 0 0 38px 0;
        }

        .trailer, .watch {
            border-radius: 18px;
            padding: 10px;
            text-decoration: none;
            transition: 1s;
            border: 1px solid transparent;
            color: #fff;
        }

        .trailer:hover, .watch:hover {
            background-color: #fff;
            border: 1px solid #333;
            color: #333;
        }

        .trailer {
            background-color: firebrick;
        }

        .watch {
            background-color: blue;
            margin: 0 0 0 34px;
        }

        .under {
            background-color: grey;
            text-align: center;
            padding: 40px 0;
        }

        .under > nav > ul > li > a {
            text-decoration: none;
            text-align: center;
            font-size: 17px;
        }

        .under > nav > ul > li > a:hover {
            text-decoration: underline;
        }

        .under > nav > ul > li {
            margin: 10px 0 0 0;
            list-style: none;
        }

    </style>
</head>
<body>
    <div class="container">
        <div class="box">
            <h1 class="title">Все фильмы</h1>
            <form action="{% url 'movies:search'%}" method="GET" role="search">
                <input type="search" type="text" name="q" placeholder="Найти интересующий фильм">
                <button type="submit">Поиск</button>
            </form>
            <ul>
                {% for i in object_list %}
                <li class="movies_item">
                    <div class="info">
                        <div>
                            <h1>{{i.name}}</h1>
                            <img src="{{i.image.url}}" alt="">
                        </div>
                        <div>
                            <p class="description">{{i.description}}</p>
                            <p class="genre">
                                <span>Жанр: </span>
                                <span>{{i.genre}}</span>
                            </p>
                            <p class="duration">{{i.duration}} минуты</p>
                            <a href="{{i.trailer}}" target="_blank" class="trailer">Смотреть трейлер</a>
                            <a href="{{i.watch}}" target="_blank" class="watch">Смотреть фильм</a>
                        </div>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class="under">
            <nav>
                <ul>
                    <li><a href="/admin/" target="_blank">Перейти в админку</a></li>
                    <li><a href="/create_movies_item/" target="_blank">Добавить фильм</a></li>
                    <li><a href="/delete_movies_item/" target="_blank">Удалить</a></li>
                    <li><a href="/edit_movies_item/" target="_blank">Редактировать</a></li>
                </ul>
            </nav>
        </div>
    </div>
</body>
</html>

HW/templates/parser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf token %}
    {{form.as_p}}
    <button type="submit">Извлечь данные</button>
</form>
</body>
</html>

HW/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Авторизация</h1>
<center>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Авторизация</button>
        <button>
            <a href="/register/">У вас есть аккаунт?</a>
        </button>
    </form>
</center>
</body>
</html>

HW/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Регистрация</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Регистрация</button>
</form>
</body>
</html>

HW/templates/users/user_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Вы успешно зарегестрировались!</h1>
<ol>
    {% for i in object_list %}
    <li>
        <h2>{{i.username}}</h2> - <em>{{i.email}}</em>
    </li>
    {% endfor %}
</ol>

<form action="{% url 'users:logout' %}">
    {% csrf_token %}
    <button type="submit">
        Выйти
    </button>
</form>
</body>
</html>